version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    container_name: playall-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: playall
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: playall-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: ["redis-server", "--save", "", "--appendonly", "no"]
volumes:
  postgres_data:
